<a href="https://colab.research.google.com/github/Deepanshu-8126/Numpy-/blob/main/NumPy_Part1_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🔢 NumPy — Part 1: Basics to Intermediate
### Complete Revision Notebook | Data Science
---
> **How to use:** Run each cell one by one. Concept + Code + Output together!
>
> **What is NumPy?**
> NumPy = Numerical Python. It is the most important library for Data Science.
> It works with **arrays** (like lists, but much faster and more powerful).
>
> **Why NumPy over Python lists?**
> - 50x faster than normal Python lists
> - Less memory usage
> - Built-in math functions (mean, sum, std...)
> - Base of Pandas, Matplotlib, Scikit-learn


## ⚙️ Setup — Run This First!

In [ ]:
import numpy as np

print("NumPy version:", np.__version__)
print("✅ NumPy imported successfully!")
print()
print("Remember: 'np' is just a short nickname for numpy")
print("Everyone in data science uses 'np'")

NumPy version: 2.0.2
✅ NumPy imported successfully!

Remember: 'np' is just a short nickname for numpy
Everyone in data science uses 'np'


---
# 📌 Topic 1 — Array Creation
**What is an Array?**
- Array = A box that stores multiple numbers
- Like a Python list BUT faster and smarter
- Every element has the same data type

**Types:**
- 1D Array → like a row: `[1, 2, 3]`
- 2D Array → like a table: `[[1,2],[3,4]]`
- 3D Array → like a cube of data


In [ ]:
# ── Topic 1A: Creating Arrays ──

# From a Python list
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)
print("Type:", type(arr1))
print("Data type of elements:", arr1.dtype)
# dtype = what kind of numbers are stored
# int64 = whole numbers | float64 = decimal numbers

print()

# 2D Array (like a table / matrix)
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print("2D Array:")
print(arr2)
print("Shape:", arr2.shape)

# shape = (rows, columns)
# (3, 3) means 3 rows and 3 columns

1D Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>
Data type of elements: int64

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)


In [ ]:
# ── Topic 1B: Special Arrays ──

# All zeros
zeros = np.zeros((3, 4))
print("Zeros (3x4):")
print(zeros)
# Use: when you want an empty array to fill later

print()

# All ones
ones = np.ones((2, 3))
print("Ones (2x3):")
print(ones)

print()

# Identity matrix (diagonal = 1, rest = 0)
identity = np.eye(3)
print("Identity Matrix (3x3):")
print(identity)
# Use: very important in Linear Algebra

print()

# Fill with any number
full = np.full((2, 4), 7)
print("Full of 7s (2x4):")
print(full)

Zeros (3x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones (2x3):
[[1. 1. 1.]
 [1. 1. 1.]]

Identity Matrix (3x3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Full of 7s (2x4):
[[7 7 7 7]
 [7 7 7 7]]


In [ ]:
# ── Topic 1C: Range Arrays ──

# arange = like Python range() but returns array
arr = np.arange(0, 10, 2)
print("arange(0, 10, 2):", arr)
# start=0, stop=10, step=2
# Output: [0, 2, 4, 6, 8]

print()

# linspace = equally spaced numbers between two points
arr2 = np.linspace(0, 1, 5)
print("linspace(0, 1, 5):", arr2)
# 5 equally spaced numbers between 0 and 1
# Output: [0.0, 0.25, 0.5, 0.75, 1.0]

print()

# Difference: arange uses step size, linspace uses count
print("arange(1, 10, 2):", np.arange(1, 10, 2))   # step=2
print("linspace(1, 10, 5):", np.linspace(1, 10, 5)) # 5 points


In [ ]:
# ── Topic 1D: Random Arrays ──

np.random.seed(42)
# seed = fix the random numbers
# same seed = same random numbers every time
# Very important for reproducibility in Data Science!

# Random integers
rand_int = np.random.randint(0, 100, (3, 4))
print("Random integers (3x4):")
print(rand_int)

print()

# Random floats between 0 and 1
rand_float = np.random.random((2, 3))
print("Random floats (2x3):")
print(rand_float)

print()

# Normal distribution (bell curve)
normal = np.random.randn(5)
print("Normal distribution (5 values):", normal)
# Most values near 0, few values far from 0
# Used in statistics and ML

print()
print("✅ Topic 1 Done!")
print("Key: np.array() | np.zeros() | np.ones() | np.arange() | np.linspace() | np.random")


---
# 📌 Topic 2 — Array Properties
**Why important?**
Before working on any array, always check its properties.
In Data Science, wrong shape = wrong results!

**Key Properties:**
- `shape` → dimensions (rows, columns)
- `ndim` → how many dimensions
- `size` → total number of elements
- `dtype` → data type of elements


In [ ]:
# ── Topic 2: Array Properties ──

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print("Array:")
print(arr)
print()

print("shape:", arr.shape)
# (3, 4) = 3 rows, 4 columns

print("ndim:", arr.ndim)
# 2 = it's a 2D array (has rows and columns)

print("size:", arr.size)
# 12 = total elements (3 x 4 = 12)

print("dtype:", arr.dtype)
# int64 = whole numbers

print("itemsize:", arr.itemsize, "bytes")
# how many bytes each element takes

print("nbytes:", arr.nbytes, "bytes")
# total memory used = itemsize x size

print()

# Check different dtypes
float_arr = np.array([1.5, 2.7, 3.14])
print("Float array dtype:", float_arr.dtype)  # float64

bool_arr = np.array([True, False, True])
print("Bool array dtype:", bool_arr.dtype)    # bool

print()
print("✅ Topic 2 Done!")
print("Key: .shape | .ndim | .size | .dtype — always check these first!")


---
# 📌 Topic 3 — Indexing & Slicing
**What is Indexing?**
- Indexing = picking one specific element
- Slicing = picking a range of elements
- Index starts from 0 (first element = index 0)
- Negative index = count from the end (-1 = last)

**This is very important in Data Science!**
You always need to pick specific rows/columns from data.


In [ ]:
# ── Topic 3A: 1D Indexing & Slicing ──

arr = np.array([10, 20, 30, 40, 50, 60, 70])
print("Array:", arr)
print()

# Single element
print("arr[0]:", arr[0])    # first = 10
print("arr[3]:", arr[3])    # index 3 = 40
print("arr[-1]:", arr[-1])  # last = 70
print("arr[-2]:", arr[-2])  # second last = 60

print()

# Slicing [start:stop:step]
print("arr[1:4]:", arr[1:4])    # index 1,2,3 → [20,30,40]
print("arr[:3]:", arr[:3])      # from start to index 2 → [10,20,30]
print("arr[4:]:", arr[4:])      # from index 4 to end → [50,60,70]
print("arr[::2]:", arr[::2])    # every 2nd element → [10,30,50,70]
print("arr[::-1]:", arr[::-1])  # reverse the array → [70,60,50,40,30,20,10]

# Dry run for arr[1:4]:
# index: 0=10, 1=20, 2=30, 3=40, 4=50...
# 1:4 means start at 1, stop BEFORE 4
# Result: [20, 30, 40]


In [ ]:
# ── Topic 3B: 2D Indexing & Slicing ──

arr2d = np.array([[1,  2,  3,  4],
                  [5,  6,  7,  8],
                  [9, 10, 11, 12]])

print("2D Array:")
print(arr2d)
print()

# Single element [row, column]
print("arr2d[0, 0]:", arr2d[0, 0])  # row 0, col 0 = 1
print("arr2d[1, 2]:", arr2d[1, 2])  # row 1, col 2 = 7
print("arr2d[2, 3]:", arr2d[2, 3])  # row 2, col 3 = 12
print("arr2d[-1, -1]:", arr2d[-1, -1])  # last row, last col = 12

print()

# Rows and Columns
print("First row arr2d[0]:", arr2d[0])         # [1, 2, 3, 4]
print("Last row arr2d[-1]:", arr2d[-1])         # [9, 10, 11, 12]
print("First column arr2d[:, 0]:", arr2d[:, 0]) # [1, 5, 9]
# [:, 0] means: all rows, column 0

print()

# Slicing 2D
print("First 2 rows, first 2 cols:")
print(arr2d[:2, :2])
# rows 0,1 and columns 0,1

print()
print("Middle block:")
print(arr2d[0:2, 1:3])
# rows 0-1, cols 1-2


In [ ]:
# ── Topic 3C: Fancy Indexing & Boolean Indexing ──

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print("Array:", arr)
print()

# Fancy Indexing = pick multiple specific indices
indices = [0, 2, 5, 7]
print("Fancy indexing [0,2,5,7]:", arr[indices])
# Pick elements at index 0, 2, 5, 7
# Output: [10, 30, 60, 80]

print()

# Boolean Indexing = pick elements based on condition
mask = arr > 40
print("Boolean mask (arr > 40):", mask)
# [False False False False True True True True]

print("Elements > 40:", arr[mask])
# Only True positions = [50, 60, 70, 80]

# Shortcut (one line)
print("Elements > 40 (shortcut):", arr[arr > 40])

print()

# Very useful in Data Science!
data = np.array([23, 45, 12, 67, 34, 89, 11, 56])
print("Data:", data)
print("Values between 30 and 70:", data[(data >= 30) & (data <= 70)])
# & = AND condition

print()
print("✅ Topic 3 Done!")
print("Key: arr[i] | arr[r,c] | arr[start:stop:step] | arr[arr>val] = Boolean indexing")


---
# 📌 Topic 4 — Reshaping Arrays
**Why Reshaping?**
- ML models need data in specific shapes
- Images are 3D arrays that need reshaping
- Changing rows/columns without changing data

**Key Rule:** Total elements must stay the same!
- `(3,4)` = 12 elements → can reshape to `(2,6)`, `(4,3)`, `(12,)` etc.


In [ ]:
# ── Topic 4A: reshape() ──

arr = np.arange(1, 13)  # [1, 2, 3, ..., 12]
print("Original array:", arr)
print("Shape:", arr.shape)  # (12,) = 1D with 12 elements

print()

# Reshape to 2D
arr_2d = arr.reshape(3, 4)
print("Reshaped to (3,4):")
print(arr_2d)

print()

arr_2d2 = arr.reshape(4, 3)
print("Reshaped to (4,3):")
print(arr_2d2)

print()

arr_2d3 = arr.reshape(2, 6)
print("Reshaped to (2,6):")
print(arr_2d3)

print()

# -1 means "NumPy, you figure out this dimension"
arr_auto = arr.reshape(3, -1)
print("reshape(3, -1):", arr_auto.shape)
# 12 / 3 = 4, so shape becomes (3,4)
# Very useful when you don't know exact size!


In [ ]:
# ── Topic 4B: flatten() and ravel() ──

arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print("2D Array:")
print(arr2d)
print()

# flatten = convert any array to 1D (makes a copy)
flat = arr2d.flatten()
print("flatten():", flat)
# [1 2 3 4 5 6 7 8 9]

# ravel = same as flatten but faster (no copy, uses same memory)
rav = arr2d.ravel()
print("ravel():", rav)

print()

# newaxis = add a new dimension
arr1d = np.array([1, 2, 3, 4, 5])
print("Original shape:", arr1d.shape)        # (5,)

row = arr1d[np.newaxis, :]
print("Row vector shape:", row.shape)         # (1, 5)

col = arr1d[:, np.newaxis]
print("Column vector shape:", col.shape)      # (5, 1)
print("Column vector:")
print(col)
# Very useful for matrix operations in ML!

print()
print("✅ Topic 4 Done!")
print("Key: reshape(r,c) | reshape(-1) | flatten() | ravel() | newaxis")


---
# 📌 Topic 5 — Array Operations
**What makes NumPy special?**
- Operations happen on the WHOLE array at once
- No need to write loops!
- This is called **Vectorization**

**Example:**
- Python list: `for i in list: i * 2` (slow loop)
- NumPy array: `arr * 2` (instant, no loop needed!)


In [ ]:
# ── Topic 5A: Basic Math Operations ──

a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("a:", a)
print("b:", b)
print()

# Operations happen element by element!
print("a + b:", a + b)    # [11, 22, 33, 44, 55]
print("b - a:", b - a)    # [9, 18, 27, 36, 45]
print("a * b:", a * b)    # [10, 40, 90, 160, 250]
print("b / a:", b / a)    # [10, 10, 10, 10, 10]
print("a ** 2:", a ** 2)  # [1, 4, 9, 16, 25] (square)
print("b % 3:", b % 3)    # remainder

print()

# Scalar operations (one number with whole array)
print("a + 100:", a + 100)  # add 100 to every element
print("a * 3:", a * 3)      # multiply every element by 3
print("a / 2:", a / 2)      # divide every element by 2

# Dry run for a + b:
# a[0]+b[0] = 1+10 = 11
# a[1]+b[1] = 2+20 = 22
# a[2]+b[2] = 3+30 = 33 ... all at once!


In [ ]:
# ── Topic 5B: Math Functions ──

arr = np.array([1, 4, 9, 16, 25, 36])
print("Array:", arr)
print()

print("Square root:", np.sqrt(arr))
# [1, 2, 3, 4, 5, 6]

print("Absolute value:", np.abs(np.array([-3, -1, 2, -5, 4])))
# removes negative sign

print("Exponential (e^x):", np.exp(np.array([0, 1, 2])))
# e^0=1, e^1=2.718, e^2=7.389

print("Log (natural):", np.log(np.array([1, np.e, np.e**2])))
# log(1)=0, log(e)=1, log(e^2)=2

print("Log base 10:", np.log10(np.array([1, 10, 100, 1000])))
# [0, 1, 2, 3]

print()

# Rounding
floats = np.array([1.234, 5.678, 9.012, 3.456])
print("Original:", floats)
print("Round 2 decimals:", np.round(floats, 2))
print("Floor (round down):", np.floor(floats))
print("Ceil (round up):", np.ceil(floats))

print()
print("✅ Topic 5A-B Done!")


In [ ]:
# ── Topic 5C: Aggregate Functions ──
# Aggregate = one function gives one summary number

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("Array:")
print(arr)
print()

# Overall (all elements)
print("Sum (all):", np.sum(arr))          # 45
print("Mean (all):", np.mean(arr))        # 5.0
print("Min (all):", np.min(arr))          # 1
print("Max (all):", np.max(arr))          # 9
print("Std deviation:", np.std(arr))      # spread of data

print()

# axis=0 = column-wise (go DOWN rows)
print("Sum axis=0 (column-wise):", np.sum(arr, axis=0))
# col0: 1+4+7=12, col1: 2+5+8=15, col2: 3+6+9=18
# Result: [12, 15, 18]

# axis=1 = row-wise (go ACROSS columns)
print("Sum axis=1 (row-wise):", np.sum(arr, axis=1))
# row0: 1+2+3=6, row1: 4+5+6=15, row2: 7+8+9=24
# Result: [6, 15, 24]

print()
print("Mean axis=0:", np.mean(arr, axis=0))  # column averages
print("Mean axis=1:", np.mean(arr, axis=1))  # row averages

print()
# argmin / argmax = index of min/max
arr1d = np.array([10, 5, 30, 15, 25])
print("Array:", arr1d)
print("argmin (index of min):", np.argmin(arr1d))  # index 1 = value 5
print("argmax (index of max):", np.argmax(arr1d))  # index 2 = value 30

print()
print("✅ Topic 5 Done!")
print("Key: sum/mean/min/max/std | axis=0 column-wise | axis=1 row-wise")


---
# 📌 Topic 6 — Broadcasting
**What is Broadcasting?**
- NumPy's ability to work with arrays of DIFFERENT shapes
- Smaller array gets "stretched" to match bigger array
- No actual copying of data — very memory efficient!

**Simple Rule:**
- If shapes match → operate directly
- If one dimension is 1 → stretch it to match

**This is used everywhere in Data Science and ML!**


In [ ]:
# ── Topic 6A: Basic Broadcasting ──

# Scalar + Array (simplest broadcasting)
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array (2x3):")
print(arr)
print()

print("arr + 10:")
print(arr + 10)
# 10 is broadcast to all elements
# Think: 10 stretches to [[10,10,10],[10,10,10]]

print()

# 1D array + 2D array
row = np.array([10, 20, 30])  # shape (3,)
print("Row:", row)
print("arr + row:")
print(arr + row)
# row [10,20,30] is added to EACH ROW of arr
# Row 0: [1+10, 2+20, 3+30] = [11, 22, 33]
# Row 1: [4+10, 5+20, 6+30] = [14, 25, 36]


In [ ]:
# ── Topic 6B: Broadcasting Rules ──

# Column vector + 2D array
col = np.array([[10],
                [20]])  # shape (2,1)
arr = np.array([[1, 2, 3],
                [4, 5, 6]])  # shape (2,3)

print("Col vector (2x1):")
print(col)
print("Array (2x3):")
print(arr)
print()

print("arr + col:")
print(arr + col)
# col [[10],[20]] added to each COLUMN
# Row 0: [1+10, 2+10, 3+10] = [11, 12, 13]
# Row 1: [4+20, 5+20, 6+20] = [24, 25, 26]

print()

# Real use case — Normalization (very common in ML!)
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]], dtype=float)

col_mean = data.mean(axis=0)  # mean of each column
col_std  = data.std(axis=0)   # std of each column

normalized = (data - col_mean) / col_std
# This is called "standardization" in ML!
print("Normalized data:")
print(normalized.round(2))

print()
print("✅ Topic 6 Done!")
print("Key: smaller array stretches to match bigger | used in ML normalization")


---
# 📌 Topic 7 — Stacking & Splitting
**Why important?**
- In Data Science, you often need to combine datasets
- Or split data into train/test sets

**Stacking** = combining arrays
**Splitting** = dividing arrays


In [ ]:
# ── Topic 7A: Stacking Arrays ──

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# vstack = vertical stack (add rows)
v = np.vstack([a, b])
print("vstack:")
print(v)
print("Shape:", v.shape)  # (2, 3)

print()

# hstack = horizontal stack (add columns)
h = np.hstack([a, b])
print("hstack:", h)  # [1 2 3 4 5 6]
print("Shape:", h.shape)  # (6,)

print()

# 2D stacking
arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])

print("vstack 2D:")
print(np.vstack([arr1, arr2]))  # add rows below
print()

print("hstack 2D:")
print(np.hstack([arr1, arr2]))  # add columns to right

print()

# concatenate = flexible stacking
print("concatenate axis=0 (rows):")
print(np.concatenate([arr1, arr2], axis=0))

print("concatenate axis=1 (cols):")
print(np.concatenate([arr1, arr2], axis=1))


In [ ]:
# ── Topic 7B: Splitting Arrays ──

arr = np.arange(1, 13)
print("Array:", arr)
print()

# split = divide into equal parts
parts = np.split(arr, 3)
# divide into 3 equal parts
print("split into 3:")
for i, part in enumerate(parts):
    print(f"  Part {i}: {part}")

print()

# hsplit = split horizontally (along columns)
arr2d = np.arange(1, 13).reshape(3, 4)
print("2D Array:")
print(arr2d)

h_parts = np.hsplit(arr2d, 2)
print("hsplit into 2:")
for i, p in enumerate(h_parts):
    print(f"  Part {i}:")
    print(f"  {p}")

print()

# vsplit = split vertically (along rows)
v_parts = np.vsplit(arr2d, 3)
print("vsplit into 3:")
for i, p in enumerate(v_parts):
    print(f"  Part {i}: {p}")

print()
print("✅ Topic 7 Done!")
print("Key: vstack=add rows | hstack=add cols | split/vsplit/hsplit = divide")


---
# 📌 Topic 8 — Copy vs View
**This is VERY important! Many bugs come from not knowing this!**

**View** = same data, different variable name (like an alias)
- Changing view → changes original too!

**Copy** = completely separate data
- Changing copy → does NOT change original

**Rule:** NumPy slicing creates a VIEW, not a copy!


In [ ]:
# ── Topic 8: Copy vs View ──

original = np.array([1, 2, 3, 4, 5])
print("Original:", original)
print()

# VIEW — shares memory with original
view = original[1:4]  # slicing creates a view!
print("View:", view)

view[0] = 999  # change view
print("After changing view[0] to 999:")
print("View:", view)
print("Original:", original)  # original also changed!
print("⚠️ View changed the original too!")

print()

# COPY — independent, does not affect original
original2 = np.array([1, 2, 3, 4, 5])
copy = original2[1:4].copy()  # .copy() makes it independent
print("Copy:", copy)

copy[0] = 888  # change copy
print("After changing copy[0] to 888:")
print("Copy:", copy)
print("Original:", original2)  # original NOT changed!
print("✅ Copy did not change the original!")

print()

# How to check if it's a view or copy
a = np.array([1, 2, 3, 4, 5])
v = a[1:3]        # view
c = a[1:3].copy() # copy

print("Is view a view?", v.base is a)   # True = it's a view
print("Is copy a view?", c.base is a)   # False = it's a copy

print()
print("✅ Topic 8 Done!")
print("Key: slicing = view (connected) | .copy() = independent | always use .copy() to be safe!")


---
# 📌 Topic 9 — Sorting & Searching
**Used in Data Science to:**
- Sort values (rankings, leaderboards)
- Find positions of max/min values
- Filter data based on conditions


In [ ]:
# ── Topic 9A: Sorting ──

arr = np.array([64, 25, 12, 45, 78, 33])
print("Original:", arr)
print()

# sort = returns sorted array (does not change original)
sorted_arr = np.sort(arr)
print("np.sort() ascending:", sorted_arr)
print("Original after sort:", arr)  # unchanged!

print()

# Descending sort
desc = np.sort(arr)[::-1]
print("Descending:", desc)

print()

# argsort = returns INDICES that would sort the array
indices = np.argsort(arr)
print("argsort (indices):", indices)
# [2, 1, 5, 3, 0, 4] means:
# smallest is at index 2 (value 12)
# then index 1 (value 25) etc.
print("Sorted values using argsort:", arr[indices])

print()

# 2D sorting
arr2d = np.array([[3, 1, 4],
                  [1, 5, 9],
                  [2, 6, 5]])
print("2D Array:")
print(arr2d)
print("Sort each row (axis=1):")
print(np.sort(arr2d, axis=1))
print("Sort each column (axis=0):")
print(np.sort(arr2d, axis=0))


In [ ]:
# ── Topic 9B: Searching ──

arr = np.array([10, 25, 30, 45, 50, 65, 70, 85])
print("Array:", arr)
print()

# where = find indices where condition is True
indices = np.where(arr > 40)
print("np.where(arr > 40):", indices)
print("Values > 40:", arr[indices])

print()

# where with replacement (if-else logic)
result = np.where(arr > 50, "High", "Low")
print("where with replacement (>50 = High, else Low):")
print(result)
# Very useful for creating categories in Data Science!

print()

# searchsorted = find where to insert value in sorted array
sorted_arr = np.array([10, 20, 30, 40, 50])
pos = np.searchsorted(sorted_arr, 35)
print("sorted_arr:", sorted_arr)
print("Insert 35 at index:", pos)  # index 3 (between 30 and 40)

print()

# any() and all()
arr2 = np.array([1, 2, 3, 4, 5])
print("arr2:", arr2)
print("Any element > 4?", np.any(arr2 > 4))   # True
print("All elements > 0?", np.all(arr2 > 0))  # True
print("All elements > 3?", np.all(arr2 > 3))  # False

print()
print("✅ Topic 9 Done!")
print("Key: sort() | argsort() | where() | any() | all()")


---
# 📌 Topic 10 — Data Type Conversion
**Why important?**
- ML models need float data, not int
- Boolean arrays used for masking
- Wrong dtype = wrong calculations or errors


In [ ]:
# ── Topic 10: Data Types ──

# Common dtypes in NumPy
print("Common NumPy dtypes:")
print("int8, int16, int32, int64  → whole numbers")
print("float32, float64           → decimal numbers")
print("bool                       → True/False")
print("complex64, complex128      → complex numbers")
print()

# Creating arrays with specific dtype
int_arr   = np.array([1, 2, 3, 4], dtype=np.int32)
float_arr = np.array([1, 2, 3, 4], dtype=np.float64)
bool_arr  = np.array([0, 1, 0, 1], dtype=bool)

print("int32:", int_arr, "dtype:", int_arr.dtype)
print("float64:", float_arr, "dtype:", float_arr.dtype)
print("bool:", bool_arr, "dtype:", bool_arr.dtype)

print()

# Type conversion with astype()
arr = np.array([1.7, 2.9, 3.1, 4.8])
print("Original float:", arr)

int_converted = arr.astype(int)
print("Converted to int:", int_converted)
# Note: it truncates (cuts off decimal), does NOT round!
# 1.7 → 1 (not 2!)

bool_converted = arr.astype(bool)
print("Converted to bool:", bool_converted)
# 0 = False, anything else = True

string_converted = arr.astype(str)
print("Converted to str:", string_converted)

print()

# Why float32 vs float64?
# float64 = more precise but uses more memory (8 bytes)
# float32 = less precise but uses less memory (4 bytes)
# In Deep Learning: float32 is preferred for speed!

print("float64 size:", np.dtype('float64').itemsize, "bytes")
print("float32 size:", np.dtype('float32').itemsize, "bytes")

print()
print("✅ Topic 10 Done!")
print("Key: astype() to convert | int truncates decimals | float32 faster in DL")


---
# 🎯 Part 1 — Quick Revision Summary

| Topic | Key Functions | Remember |
|-------|--------------|----------|
| Array Creation | `np.array()`, `zeros()`, `ones()`, `arange()`, `linspace()` | seed=42 for reproducibility |
| Properties | `.shape`, `.ndim`, `.size`, `.dtype` | Check these first always! |
| Indexing | `arr[i]`, `arr[r,c]`, `arr[start:stop:step]` | Starts from 0, -1=last |
| Reshaping | `reshape()`, `flatten()`, `ravel()` | Total elements must stay same |
| Operations | `+,-,*,/`, `np.sqrt()`, `np.sum()` | No loops needed! |
| Broadcasting | Different shapes work together | Smaller array stretches |
| Stacking | `vstack`, `hstack`, `concatenate` | v=rows, h=cols |
| Copy vs View | `.copy()` | Slicing = view! Use .copy() to be safe |
| Sorting | `np.sort()`, `np.argsort()`, `np.where()` | argsort gives indices |
| Data Types | `.astype()`, `dtype=` | int truncates, float32 faster in DL |

---
## ⚡ One-Liners to Remember
```python
np.arange(0, 10, 2)          # [0,2,4,6,8]
np.linspace(0, 1, 5)         # 5 points 0 to 1
arr.reshape(3, -1)            # -1 = auto calculate
arr[arr > 50]                 # boolean indexing
np.where(arr > 50, "H", "L") # condition replacement
arr.copy()                    # safe copy
np.argsort(arr)               # sorted indices
np.sum(arr, axis=0)           # column-wise sum
np.sum(arr, axis=1)           # row-wise sum
```

---
### 🔥 Part 1 Complete! Open Part 2 for Advanced NumPy!


In [ ]:
print("🎉 NumPy Part 1 Complete!")
print()
print("✅ Topic 1  — Array Creation")
print("✅ Topic 2  — Array Properties")
print("✅ Topic 3  — Indexing & Slicing")
print("✅ Topic 4  — Reshaping")
print("✅ Topic 5  — Array Operations")
print("✅ Topic 6  — Broadcasting")
print("✅ Topic 7  — Stacking & Splitting")
print("✅ Topic 8  — Copy vs View")
print("✅ Topic 9  — Sorting & Searching")
print("✅ Topic 10 — Data Types")
print()
print("➡️ Open NumPy_Part2_Advanced.ipynb for more!")
