Numpy-- numerical python

In [3]:
import numpy as np # alias

**Array creation**

In [4]:
# 1- manual way makig list inside tuple
arr=np.array([1,2,3])
print(arr) #123

# 2 method arange
arr=np.arange(1,10)
print(arr) #123456789

# 3 method
arr=np.array(range(1,10))
print(arr) #123456789


[1 2 3]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


RESHAPE(1d to 2d )

In [5]:
a=np.arange(12).reshape(2,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [6]:
# dimensions  and shape of the array
arr=np.array(34)
arr.ndim

0

In [7]:
# 1 bracket one dimension
# 2 bracket two dimension
a=np.array([]) # 1
a.ndim
b=np.array([[]]) #2 dimension
b.ndim
c= np.array([[[]]]) # 3d
c.ndim
d= np.array([[[[]]]]) # 4d
d.ndim
# check the shape of the array
d.shape #


(1, 1, 1, 0)

In [8]:
# dtype
a=np.array([1,2,3],dtype=float)
print(a) # behace like float
print(a.dtype) # float64
print(a.astype(np.float32))


[1. 2. 3.]
float64
[1. 2. 3.]


ARRAY CREATION BY GIVINIG RANGE

In [9]:
 # Giving Range to create no of arrays (loop) np.arange
# range of numbers  ( start stop step )
a=np.arange(1,10)
print(a) # 1 2 3 4 5 6 7 8 9

#  step value

a = np.arange(1,10,2)
print(a) # 1 3 5 7 9

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


LINSPACE -- GENERATE NUMBERS BETWEN -10 TO +10

In [10]:
# Topic - Array creation linspace -- ( GRAPH )Evenly spaced between two numbers
arr= np.linspace(0,1,5) # 0 to 1
print(arr)  # 0 0.25 0.5 0.75 1.

arr = np.linspace(0,5,10) # need 10 evenly spaced
print(arr)

arr=np.linspace(-10,10,5,dtype=int) # integer type data
print(arr)


[0.   0.25 0.5  0.75 1.  ]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[-10  -5   0   5  10]


In [11]:
# Logspace --

arr= np.logspace(1,3,3)  # logartihmic scale array 10^1 10^2 10^3 .. 3 points
print(arr)

arr=np.logspace(1,3,2) # 2 points
print(arr)   # 10 1000


[  10.  100. 1000.]
[  10. 1000.]


In [12]:
#np.logspace(start,ending -> powers,3)

NUMPY ZEROS AND ONES IDENTITY , FULL

In [13]:
# Topic -- zeroes and ones
# this create an array  full of zeroes np.zeros

arr=np.zeros(5)
print(arr) #  5 elements only

# i  need 2 * 3 matrix of zeroes

a=np.zeros([2,3])
print(a)
print(a.size) # total elements 6



[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
6


In [14]:
# Ones
arr=np.ones(2) # 2 elements of 1 1
print(arr)

arr = np.ones([2,3]) # 2 * 3
print(arr)

[1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# FULL function
arr = np.full(10,2) # 10 element of 2 (1d array)
print(arr)

[2 2 2 2 2 2 2 2 2 2]


IDENTITY (NP.IDENETIY)

In [16]:
a=np.identity(3)
print(a) # diagonal matrix 3 by 3 matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
# 2d array
# parameters - ([rows, colummns ], default value )

arr = np.full([2,3],7) # 2,3 matrix of 6 elements of 7 predefault 7 values
print(arr)

[[7 7 7]
 [7 7 7]]


In [18]:
# uninitalized array - create an array  without setting any sorting any values
arr=np.empty([2,3]) # pass dimensions this is uninitialized arrayz
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
list=[1,2,3,4,5]
a=list*2
print(a)
arr = np.array([1,2,3,4,5])
b= arr * 2
print(b)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [20]:
# Numpy Data Types and Type casting
arr = np.array([1,2,4,5,5])
print(type(arr))

<class 'numpy.ndarray'>


In [21]:
lst=[1,2,3,4,5]
arr= np.array(lst)
print(arr)
print(type(arr))
print(arr.dtype) #int 64


[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


converted to float 32 and float 64

In [22]:
arr = np.array([1,2,3,4],dtype=  np.float32)
print(arr.dtype)

arr = np.array([1,2,3,4,5],dtype=np.float64)
print(arr.dtype) #float64

float32
float64


Float to int reverse

In [23]:
arr = np.array([1.1,2.1,3,4],dtype=  np.int32)
print(arr.dtype)

int32


In [24]:
# Typecasting - covert one datatype to another datatype
# astype
arr=np.array([1,2,3])
print(arr.dtype) # default datatype is int 64 or float 64

int64


CONVERT INT64 TO FLOAT64

In [25]:
a=np.array([1,2,3])
new_arr=a.astype(np.float64)
print(new_arr)

# if we check datatype now
print(new_arr.dtype) # float64

[1. 2. 3.]
float64


In [26]:
# Type Casting Erros
"""arr=np.array(["1","2","hello"])
arr2=arr.astype(np.int64)
print(arr2) # invalid hello multiple chacters"""

# we cannot covert string into integer or vice versa
# only same type of data contains

'arr=np.array(["1","2","hello"])\narr2=arr.astype(np.int64)\nprint(arr2) # invalid hello multiple chacters'

-->> we can create 2d 3d 4d as onn


In [27]:
a = np.array([1,2,3])
b=np.array([[1,2,3],
            [4,5,6]])
c=np.array([[[1,2],[3,4],[5,6]]])

# lets check there dimensions
print(a.ndim)  #1
print(b.ndim)  #2
print(c.ndim)  #3

# shape check
print(a.shape)
print(b.shape)
print(c.shape)

# also change or check datatype
d=np.array([1,2,3],dtype=float)
print(d)

# reshape
a=np.arange(1,11)
a.reshape(5,2)
a=np.random.random((1,11))
print(a)

1
2
3
(3,)
(2, 3)
(1, 3, 2)
[1. 2. 3.]
[[0.0971032  0.71538308 0.72088296 0.53166395 0.17361336 0.95275547
  0.65375818 0.65583251 0.97117683 0.23912447 0.88195685]]


**ARRAY ATTRIBUTES  (size , shape ,ndim, itemsize, dtype)**

In [28]:
a1=np.arange(1,11)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

#ndim-
a1.ndim
a2.ndim
a3.ndim
a1.shape
a2.shape
a3.shape
a1.size
a2.size
a3.size

# itemsize
a=a1.itemsize
print(a)

#dtype tells type
print(a1.dtype)  # int64

# changing datatype
#astype
a3.astype(np.int32)

8
int64


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [29]:
# ndim nshape nsize itemsizd

------------------Questtions ---


In [30]:
import numpy as np
arr=np.random.rand(10).reshape(2,5)
print(arr)

[[0.54208986 0.11652749 0.3682682  0.42149247 0.12667106]
 [0.48849425 0.50330618 0.08497682 0.37672768 0.44357845]]


In [31]:
arr=np.ones(12).reshape(2,6)
print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


Array operations

In [32]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [43]:
# scalar operations
# arithmethic
a=np.array([1,2,3,4,5])
print(a)
print(a+1)
print(a*2)
print(a/3)
print(a//2)

# relational operator - return boolean values
print(a>=5)
print(a<2)
print(a==2)




[1 2 3 4 5]
[2 3 4 5 6]
[ 2  4  6  8 10]
[0.33333333 0.66666667 1.         1.33333333 1.66666667]
[0 1 1 2 2]
[False False False False  True]
[ True False False False False]
[False  True False False False]


In [45]:
# vector operations
print(a1)
print(a2)
print(a1+a2)
print(a1-a2)

print(a1>a2)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
[[False False False False]
 [False False False False]
 [False False False False]]


In [60]:
# Array functions
a1=np.arange(1,11)
a1=np.random.random((3,3))
a1=np.round(a1*100)
print(a1)

# max min sum prod
print(np.max(a1)) # float value return
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))




[[19. 73. 13.]
 [27. 65. 48.]
 [ 1. 52. 80.]]
80.0
1.0
378.0
6318754790400.0


In [66]:
# axis wise operation
print(a1)
print(np.max(a1,axis=0)) # max item in every column return
print(np.min(a1,axis=1))
print(np.sum(a1,axis=1))
print(np.prod(a1,axis=1))

[[19. 73. 13.]
 [27. 65. 48.]
 [ 1. 52. 80.]]
[27. 73. 80.]
[13. 27.  1.]
[105. 140. 133.]
[18031. 84240.  4160.]


In [78]:
# mean median variance std
print(np.mean(a1))
print(np.mean(a1,axis=1))
print(np.std(a1,axis=1))
print(np.var(a1,axis=1))
print(np.median(a1))
print(np.median(a1,axis=1))

42.0
[35.         46.66666667 44.33333333]
[26.98147513 15.54205764 32.70406023]
[ 728.          241.55555556 1069.55555556]
48.0
[19. 48. 52.]


In [81]:
# trignometric functions
print(np.sin(a1))
print(np.cos(a1))
print(np.tan(a1))

[[ 0.14987721 -0.67677196  0.42016704]
 [ 0.95637593  0.82682868 -0.76825466]
 [ 0.84147098  0.98662759 -0.99388865]]
[[ 0.98870462 -0.73619272  0.90744678]
 [-0.29213881 -0.56245385 -0.64014434]
 [ 0.54030231 -0.16299078 -0.11038724]]
[[ 0.15158947  0.9192864   0.46302113]
 [-3.2737038  -1.47003826  1.20012724]
 [ 1.55740772 -6.05327238  9.00365495]]


In [84]:
# dot product  conditon
print(a1)
print(a2)
print(np.dot(a1,a2))

[[19. 73. 13.]
 [27. 65. 48.]
 [ 1. 52. 80.]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[1656. 1761. 1866. 1971.]
 [2324. 2464. 2604. 2744.]
 [2444. 2577. 2710. 2843.]]


In [85]:
# log and exp
print(np.log(a1))
print(np.exp(a1))

[[2.94443898 4.29045944 2.56494936]
 [3.29583687 4.17438727 3.87120101]
 [0.         3.95124372 4.38202663]]
[[1.78482301e+08 5.05239363e+31 4.42413392e+05]
 [5.32048241e+11 1.69488924e+28 7.01673591e+20]
 [2.71828183e+00 3.83100800e+22 5.54062238e+34]]


In [89]:
# round floor ceil
a=np.random.random((2,3))*100
print(a)
print(np.round(a))
print(np.floor(a))
print(np.ceil(a))

[[20.6742545  59.43114595 11.70907996]
 [ 6.60666349 47.84439263 24.66402447]]
[[21. 59. 12.]
 [ 7. 48. 25.]]
[[20. 59. 11.]
 [ 6. 47. 24.]]
[[21. 60. 12.]
 [ 7. 48. 25.]]


INDEXING


In [97]:
a1=np.arange(20)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

# slicing and indexing
print(a1)
# acess using indexing
print(a1[0],a1[10]) # one and two also



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
0 10


In [101]:
# for 2d arrays
print(a2)
# i want 6
print(a2[1,2])
# 11
print(a2[2,3])



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
11


In [106]:
# FOR 3D (TENSOR) (indexing)
print(a3)
print(a3[0,0,1]) # 1

print(a3[1,1,1]) # 7

# 2 need
print(a3[0,1,0])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
1
7
2


SLICING(imp)

In [111]:
# SLICING IN 1D
print(a1)


# slicing
print(a1[1:6])

# 10 to 12 only

print(a1[10:13])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1 2 3 4 5]
[10 11 12]
