Numpy-- numerical python

In [2]:
import numpy as np # alias

**Array creation**

In [3]:
# 1- manual way makig list inside tuple
arr=np.array([1,2,3])
print(arr) #123

# 2 method arange
arr=np.arange(1,10)
print(arr) #123456789

# 3 method
arr=np.array(range(1,10))
print(arr) #123456789


[1 2 3]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


RESHAPE(1d to 2d )

In [4]:
a=np.arange(12).reshape(2,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [5]:
# dimensions  and shape of the array
arr=np.array(34)
arr.ndim

0

In [6]:
# 1 bracket one dimension
# 2 bracket two dimension
a=np.array([]) # 1
a.ndim
b=np.array([[]]) #2 dimension
b.ndim
c= np.array([[[]]]) # 3d
c.ndim
d= np.array([[[[]]]]) # 4d
d.ndim
# check the shape of the array
d.shape #


(1, 1, 1, 0)

In [7]:
# dtype
a=np.array([1,2,3],dtype=float)
print(a) # behace like float
print(a.dtype) # float64
print(a.astype(np.float32))


[1. 2. 3.]
float64
[1. 2. 3.]


ARRAY CREATION BY GIVINIG RANGE

In [8]:
 # Giving Range to create no of arrays (loop) np.arange
# range of numbers  ( start stop step )
a=np.arange(1,10)
print(a) # 1 2 3 4 5 6 7 8 9

#  step value

a = np.arange(1,10,2)
print(a) # 1 3 5 7 9

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


LINSPACE -- GENERATE NUMBERS BETWEN -10 TO +10

In [9]:
# Topic - Array creation linspace -- ( GRAPH )Evenly spaced between two numbers
arr= np.linspace(0,1,5) # 0 to 1
print(arr)  # 0 0.25 0.5 0.75 1.

arr = np.linspace(0,5,10) # need 10 evenly spaced
print(arr)

arr=np.linspace(-10,10,5,dtype=int) # integer type data
print(arr)


[0.   0.25 0.5  0.75 1.  ]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[-10  -5   0   5  10]


In [10]:
# Logspace --

arr= np.logspace(1,3,3)  # logartihmic scale array 10^1 10^2 10^3 .. 3 points
print(arr)

arr=np.logspace(1,3,2) # 2 points
print(arr)   # 10 1000


[  10.  100. 1000.]
[  10. 1000.]


In [11]:
#np.logspace(start,ending -> powers,3)

NUMPY ZEROS AND ONES IDENTITY , FULL

In [12]:
# Topic -- zeroes and ones
# this create an array  full of zeroes np.zeros

arr=np.zeros(5)
print(arr) #  5 elements only

# i  need 2 * 3 matrix of zeroes

a=np.zeros([2,3])
print(a)
print(a.size) # total elements 6



[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
6


In [13]:
# Ones
arr=np.ones(2) # 2 elements of 1 1
print(arr)

arr = np.ones([2,3]) # 2 * 3
print(arr)

[1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# FULL function
arr = np.full(10,2) # 10 element of 2 (1d array)
print(arr)

[2 2 2 2 2 2 2 2 2 2]


IDENTITY (NP.IDENETIY)

In [15]:
a=np.identity(3)
print(a) # diagonal matrix 3 by 3 matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# 2d array
# parameters - ([rows, colummns ], default value )

arr = np.full([2,3],7) # 2,3 matrix of 6 elements of 7 predefault 7 values
print(arr)

[[7 7 7]
 [7 7 7]]


In [17]:
# uninitalized array - create an array  without setting any sorting any values
arr=np.empty([2,3]) # pass dimensions this is uninitialized arrayz
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
list=[1,2,3,4,5]
a=list*2
print(a)
arr = np.array([1,2,3,4,5])
b= arr * 2
print(b)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [19]:
# Numpy Data Types and Type casting
arr = np.array([1,2,4,5,5])
print(type(arr))

<class 'numpy.ndarray'>


In [20]:
lst=[1,2,3,4,5]
arr= np.array(lst)
print(arr)
print(type(arr))
print(arr.dtype) #int 64


[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


converted to float 32 and float 64

In [21]:
arr = np.array([1,2,3,4],dtype=  np.float32)
print(arr.dtype)

arr = np.array([1,2,3,4,5],dtype=np.float64)
print(arr.dtype) #float64

float32
float64


Float to int reverse

In [22]:
arr = np.array([1.1,2.1,3,4],dtype=  np.int32)
print(arr.dtype)

int32


In [23]:
# Typecasting - covert one datatype to another datatype
# astype
arr=np.array([1,2,3])
print(arr.dtype) # default datatype is int 64 or float 64

int64


CONVERT INT64 TO FLOAT64

In [24]:
a=np.array([1,2,3])
new_arr=a.astype(np.float64)
print(new_arr)

# if we check datatype now
print(new_arr.dtype) # float64

[1. 2. 3.]
float64


In [25]:
# Type Casting Erros
"""arr=np.array(["1","2","hello"])
arr2=arr.astype(np.int64)
print(arr2) # invalid hello multiple chacters"""

# we cannot covert string into integer or vice versa
# only same type of data contains

'arr=np.array(["1","2","hello"])\narr2=arr.astype(np.int64)\nprint(arr2) # invalid hello multiple chacters'

-->> we can create 2d 3d 4d as onn


In [26]:
a = np.array([1,2,3])
b=np.array([[1,2,3],
            [4,5,6]])
c=np.array([[[1,2],[3,4],[5,6]]])

# lets check there dimensions
print(a.ndim)  #1
print(b.ndim)  #2
print(c.ndim)  #3

# shape check
print(a.shape)
print(b.shape)
print(c.shape)

# also change or check datatype
d=np.array([1,2,3],dtype=float)
print(d)

# reshape
a=np.arange(1,11)
a.reshape(5,2)
a=np.random.random((1,11))
print(a)

1
2
3
(3,)
(2, 3)
(1, 3, 2)
[1. 2. 3.]
[[0.27958682 0.34488403 0.32782578 0.61718884 0.70534543 0.95422857
  0.15707987 0.82724515 0.35550504 0.39848355 0.91008053]]


**ARRAY ATTRIBUTES  (size , shape ,ndim, itemsize, dtype)**

In [27]:
a1=np.arange(1,11)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

#ndim-
a1.ndim
a2.ndim
a3.ndim
a1.shape
a2.shape
a3.shape
a1.size
a2.size
a3.size

# itemsize
a=a1.itemsize
print(a)

#dtype tells type
print(a1.dtype)  # int64

# changing datatype
#astype
a3.astype(np.int32)

8
int64


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [28]:
# ndim nshape nsize itemsizd

------------------Questtions ---


In [29]:
import numpy as np
arr=np.random.rand(10).reshape(2,5)
print(arr)

[[0.42870643 0.76948135 0.97915368 0.22158917 0.6617743 ]
 [0.4215439  0.76945371 0.5840031  0.99672875 0.82736331]]


In [30]:
arr=np.ones(12).reshape(2,6)
print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


Array operations

In [31]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [32]:
# scalar operations
# arithmethic
a=np.array([1,2,3,4,5])
print(a)
print(a+1)
print(a*2)
print(a/3)
print(a//2)

# relational operator - return boolean values
print(a>=5)
print(a<2)
print(a==2)




[1 2 3 4 5]
[2 3 4 5 6]
[ 2  4  6  8 10]
[0.33333333 0.66666667 1.         1.33333333 1.66666667]
[0 1 1 2 2]
[False False False False  True]
[ True False False False False]
[False  True False False False]


In [33]:
# vector operations
print(a1)
print(a2)
print(a1+a2)
print(a1-a2)

print(a1>a2)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
[[False False False False]
 [False False False False]
 [False False False False]]


In [34]:
# Array functions
a1=np.arange(1,11)
a1=np.random.random((3,3))
a1=np.round(a1*100)
print(a1)

# max min sum prod
print(np.max(a1)) # float value return
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))




[[91. 98. 13.]
 [35. 75. 85.]
 [50. 47. 87.]]
98.0
13.0
581.0
5288666343187500.0


In [35]:
# axis wise operation
print(a1)
print(np.max(a1,axis=0)) # max item in every column return
print(np.min(a1,axis=1))
print(np.sum(a1,axis=1))
print(np.prod(a1,axis=1))

[[91. 98. 13.]
 [35. 75. 85.]
 [50. 47. 87.]]
[91. 98. 87.]
[13. 35. 47.]
[202. 195. 184.]
[115934. 223125. 204450.]


In [36]:
# mean median variance std
print(np.mean(a1))
print(np.mean(a1,axis=1))
print(np.std(a1,axis=1))
print(np.var(a1,axis=1))
print(np.median(a1))
print(np.median(a1,axis=1))

64.55555555555556
[67.33333333 65.         61.33333333]
[38.52560476 21.60246899 18.19035153]
[1484.22222222  466.66666667  330.88888889]
75.0
[91. 75. 50.]


In [37]:
# trignometric functions
print(np.sin(a1))
print(np.cos(a1))
print(np.tan(a1))

[[ 0.10598751 -0.57338187  0.42016704]
 [-0.42818267 -0.38778164 -0.17607562]
 [-0.26237485  0.12357312 -0.82181784]]
[[-0.99436746 -0.81928825  0.90744678]
 [-0.90369221  0.92175127 -0.98437664]
 [ 0.96496603 -0.99233547  0.56975033]]
[[-0.10658787  0.69985365  0.46302113]
 [ 0.47381472 -0.42070095  0.17887017]
 [-0.27190061 -0.12452757 -1.44241747]]


In [38]:
# dot product  conditon
print(a1)
print(a2)
print(np.dot(a1,a2))

[[91. 98. 13.]
 [35. 75. 85.]
 [50. 47. 87.]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[2920. 3122. 3324. 3526.]
 [3320. 3515. 3710. 3905.]
 [3092. 3276. 3460. 3644.]]


In [39]:
# log and exp
print(np.log(a1))
print(np.exp(a1))

[[4.51085951 4.58496748 2.56494936]
 [3.55534806 4.31748811 4.44265126]
 [3.91202301 3.8501476  4.46590812]]
[[3.31740010e+39 3.63797095e+42 4.42413392e+05]
 [1.58601345e+15 3.73324200e+32 8.22301271e+36]
 [5.18470553e+21 2.58131289e+20 6.07603023e+37]]


In [40]:
# round floor ceil
a=np.random.random((2,3))*100
print(a)
print(np.round(a))
print(np.floor(a))
print(np.ceil(a))

[[26.81403001 19.18051364 15.2929387 ]
 [23.32668615 33.33710061 37.58288382]]
[[27. 19. 15.]
 [23. 33. 38.]]
[[26. 19. 15.]
 [23. 33. 37.]]
[[27. 20. 16.]
 [24. 34. 38.]]


INDEXING


In [41]:
a1=np.arange(20)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

# slicing and indexing
print(a1)
# acess using indexing
print(a1[0],a1[10]) # one and two also



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
0 10


In [42]:
# for 2d arrays
print(a2)
# i want 6
print(a2[1,2])
# 11
print(a2[2,3])



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
11


In [43]:
# FOR 3D (TENSOR) (indexing)
print(a3)
print(a3[0,0,1]) # 1

print(a3[1,1,1]) # 7

# 2 need
print(a3[0,1,0])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
1
7
2


SLICING(imp)

In [44]:
# SLICING IN 1D
print(a1)


# slicing
print(a1[1:6])

# 10 to 12 only

print(a1[10:13])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1 2 3 4 5]
[10 11 12]


In [45]:
# slicing in 2d
print(a2)

# 1st row
print(a2[:1])

# third column
print(a2[:,2])
print(a2[2:]) # 8 9 10 11

# 5 6
# 9 10
print(a2[1:,1:3])


# 0 3
# 8 11
print(a2[::2,::3]) # excusive so 3


# 1 3
# 9 11
print(a2[::2,1::2])

# 4 7
print(a2[1,::3])

print(a2[1::,1::])

print(a2[0:2,1:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2 3]]
[ 2  6 10]
[[ 8  9 10 11]]
[[ 5  6]
 [ 9 10]]
[[ 0  3]
 [ 8 11]]
[[ 1  3]
 [ 9 11]]
[4 7]
[[ 5  6  7]
 [ 9 10 11]]
[[1 2 3]
 [5 6 7]]


In [75]:
# slicing in 3d array

# slicing arr[layer,row,colummn]


np.int64(1)

In [77]:
# Iterating loop
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [78]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [81]:
for i in np.nditer(a3): #nditer convert 3d to 1d array
  print(i)

0
1
2
3
4
5
6
7


RESHAPING

In [88]:
#reshape
#transpose
#flatten
a1
print(a1.flatten()) # flat array
a2.ravel() # any dim convert to 1d

# transpose
a2.T

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

STACKING
Types Horizontal stack
Vertical stack

In [97]:
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
print(a4)
print(a5)
# horizontal stack ( inside tuple)
np.hstack((a4,a5))  # colmn add

# 3*4 -- 3*4 == 24 items total

np.vstack((a4,a5))  # row add


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Where use using databse analysis stack

In [100]:
# splitting (opposite of stack)
np.hsplit(a4,2)  # 2 equal parts


np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]