Numpy-- numerical python

In [2]:
import numpy as np # alias

**Array creation**

In [3]:
# 1- manual way makig list inside tuple
arr=np.array([1,2,3])
print(arr) #123

# 2 method arange
arr=np.arange(1,10)
print(arr) #123456789

# 3 method
arr=np.array(range(1,10))
print(arr) #123456789


[1 2 3]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


RESHAPE(1d to 2d )

In [4]:
a=np.arange(12).reshape(2,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [5]:
# dimensions  and shape of the array
arr=np.array(34)
arr.ndim

0

In [6]:
# 1 bracket one dimension
# 2 bracket two dimension
a=np.array([]) # 1
a.ndim
b=np.array([[]]) #2 dimension
b.ndim
c= np.array([[[]]]) # 3d
c.ndim
d= np.array([[[[]]]]) # 4d
d.ndim
# check the shape of the array
d.shape #


(1, 1, 1, 0)

In [7]:
# dtype
a=np.array([1,2,3],dtype=float)
print(a) # behace like float
print(a.dtype) # float64
print(a.astype(np.float32))


[1. 2. 3.]
float64
[1. 2. 3.]


ARRAY CREATION BY GIVINIG RANGE

In [8]:
 # Giving Range to create no of arrays (loop) np.arange
# range of numbers  ( start stop step )
a=np.arange(1,10)
print(a) # 1 2 3 4 5 6 7 8 9

#  step value

a = np.arange(1,10,2)
print(a) # 1 3 5 7 9

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


LINSPACE -- GENERATE NUMBERS BETWEN -10 TO +10

In [9]:
# Topic - Array creation linspace -- ( GRAPH )Evenly spaced between two numbers
arr= np.linspace(0,1,5) # 0 to 1
print(arr)  # 0 0.25 0.5 0.75 1.

arr = np.linspace(0,5,10) # need 10 evenly spaced
print(arr)

arr=np.linspace(-10,10,5,dtype=int) # integer type data
print(arr)


[0.   0.25 0.5  0.75 1.  ]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[-10  -5   0   5  10]


In [10]:
# Logspace --

arr= np.logspace(1,3,3)  # logartihmic scale array 10^1 10^2 10^3 .. 3 points
print(arr)

arr=np.logspace(1,3,2) # 2 points
print(arr)   # 10 1000


[  10.  100. 1000.]
[  10. 1000.]


In [11]:
#np.logspace(start,ending -> powers,3)

NUMPY ZEROS AND ONES IDENTITY , FULL

In [12]:
# Topic -- zeroes and ones
# this create an array  full of zeroes np.zeros

arr=np.zeros(5)
print(arr) #  5 elements only

# i  need 2 * 3 matrix of zeroes

a=np.zeros([2,3])
print(a)
print(a.size) # total elements 6



[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
6


In [13]:
# Ones
arr=np.ones(2) # 2 elements of 1 1
print(arr)

arr = np.ones([2,3]) # 2 * 3
print(arr)

[1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# FULL function
arr = np.full(10,2) # 10 element of 2 (1d array)
print(arr)

[2 2 2 2 2 2 2 2 2 2]


IDENTITY (NP.IDENETIY)

In [15]:
a=np.identity(3)
print(a) # diagonal matrix 3 by 3 matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# 2d array
# parameters - ([rows, colummns ], default value )

arr = np.full([2,3],7) # 2,3 matrix of 6 elements of 7 predefault 7 values
print(arr)

[[7 7 7]
 [7 7 7]]


In [17]:
# uninitalized array - create an array  without setting any sorting any values
arr=np.empty([2,3]) # pass dimensions this is uninitialized arrayz
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
list=[1,2,3,4,5]
a=list*2
print(a)
arr = np.array([1,2,3,4,5])
b= arr * 2
print(b)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [19]:
# Numpy Data Types and Type casting
arr = np.array([1,2,4,5,5])
print(type(arr))

<class 'numpy.ndarray'>


In [20]:
lst=[1,2,3,4,5]
arr= np.array(lst)
print(arr)
print(type(arr))
print(arr.dtype) #int 64


[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


converted to float 32 and float 64

In [21]:
arr = np.array([1,2,3,4],dtype=  np.float32)
print(arr.dtype)

arr = np.array([1,2,3,4,5],dtype=np.float64)
print(arr.dtype) #float64

float32
float64


Float to int reverse

In [22]:
arr = np.array([1.1,2.1,3,4],dtype=  np.int32)
print(arr.dtype)

int32


In [23]:
# Typecasting - covert one datatype to another datatype
# astype
arr=np.array([1,2,3])
print(arr.dtype) # default datatype is int 64 or float 64

int64


CONVERT INT64 TO FLOAT64

In [24]:
a=np.array([1,2,3])
new_arr=a.astype(np.float64)
print(new_arr)

# if we check datatype now
print(new_arr.dtype) # float64

[1. 2. 3.]
float64


In [25]:
# Type Casting Erros
"""arr=np.array(["1","2","hello"])
arr2=arr.astype(np.int64)
print(arr2) # invalid hello multiple chacters"""

# we cannot covert string into integer or vice versa
# only same type of data contains

'arr=np.array(["1","2","hello"])\narr2=arr.astype(np.int64)\nprint(arr2) # invalid hello multiple chacters'

-->> we can create 2d 3d 4d as onn


In [26]:
a = np.array([1,2,3])
b=np.array([[1,2,3],
            [4,5,6]])
c=np.array([[[1,2],[3,4],[5,6]]])

# lets check there dimensions
print(a.ndim)  #1
print(b.ndim)  #2
print(c.ndim)  #3

# shape check
print(a.shape)
print(b.shape)
print(c.shape)

# also change or check datatype
d=np.array([1,2,3],dtype=float)
print(d)

# reshape
a=np.arange(1,11)
a.reshape(5,2)
a=np.random.random((1,11))
print(a)

1
2
3
(3,)
(2, 3)
(1, 3, 2)
[1. 2. 3.]
[[0.36695421 0.26291094 0.32036647 0.05509662 0.62371927 0.75895749
  0.2333247  0.33215321 0.02289498 0.59851975 0.41306074]]


**ARRAY ATTRIBUTES  (size , shape ,ndim, itemsize, dtype)**

In [27]:
a1=np.arange(1,11)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

#ndim-
a1.ndim
a2.ndim
a3.ndim
a1.shape
a2.shape
a3.shape
a1.size
a2.size
a3.size

# itemsize
a=a1.itemsize
print(a)

#dtype tells type
print(a1.dtype)  # int64

# changing datatype
#astype
a3.astype(np.int32)

8
int64


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [28]:
# ndim nshape nsize itemsizd

------------------Questtions ---


In [29]:
import numpy as np
arr=np.random.rand(10).reshape(2,5)
print(arr)

[[0.71849757 0.60028458 0.88689825 0.32609785 0.5164912 ]
 [0.46831766 0.18591951 0.54891366 0.20386399 0.18038943]]


In [30]:
arr=np.ones(12).reshape(2,6)
print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


Array operations

In [31]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [32]:
# scalar operations
# arithmethic
a=np.array([1,2,3,4,5])
print(a)
print(a+1)
print(a*2)
print(a/3)
print(a//2)

# relational operator - return boolean values
print(a>=5)
print(a<2)
print(a==2)




[1 2 3 4 5]
[2 3 4 5 6]
[ 2  4  6  8 10]
[0.33333333 0.66666667 1.         1.33333333 1.66666667]
[0 1 1 2 2]
[False False False False  True]
[ True False False False False]
[False  True False False False]


In [33]:
# vector operations
print(a1)
print(a2)
print(a1+a2)
print(a1-a2)

print(a1>a2)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
[[False False False False]
 [False False False False]
 [False False False False]]


In [34]:
# Array functions
a1=np.arange(1,11)
a1=np.random.random((3,3))
a1=np.round(a1*100)
print(a1)

# max min sum prod
print(np.max(a1)) # float value return
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))




[[ 99.  27. 100.]
 [ 69.  50.  15.]
 [ 44.  24.  10.]]
100.0
10.0
438.0
146074104000000.0


In [35]:
# axis wise operation
print(a1)
print(np.max(a1,axis=0)) # max item in every column return
print(np.min(a1,axis=1))
print(np.sum(a1,axis=1))
print(np.prod(a1,axis=1))

[[ 99.  27. 100.]
 [ 69.  50.  15.]
 [ 44.  24.  10.]]
[ 99.  50. 100.]
[27. 15. 10.]
[226. 134.  78.]
[267300.  51750.  10560.]


In [36]:
# mean median variance std
print(np.mean(a1))
print(np.mean(a1,axis=1))
print(np.std(a1,axis=1))
print(np.var(a1,axis=1))
print(np.median(a1))
print(np.median(a1,axis=1))

48.666666666666664
[75.33333333 44.66666667 26.        ]
[34.17926597 22.36564826 13.95229969]
[1168.22222222  500.22222222  194.66666667]
44.0
[99. 50. 24.]


In [37]:
# trignometric functions
print(np.sin(a1))
print(np.cos(a1))
print(np.tan(a1))

[[-0.99920683  0.95637593 -0.50636564]
 [-0.11478481 -0.26237485  0.65028784]
 [ 0.01770193 -0.90557836 -0.54402111]]
[[ 0.03982088 -0.29213881  0.86231887]
 [ 0.99339038  0.96496603 -0.75968791]
 [ 0.99984331  0.42417901 -0.83907153]]
[[-2.50925350e+01 -3.27370380e+00 -5.87213915e-01]
 [-1.15548546e-01 -2.71900612e-01 -8.55993401e-01]
 [ 1.77046993e-02 -2.13489670e+00  6.48360827e-01]]


In [38]:
# dot product  conditon
print(a1)
print(a2)
print(np.dot(a1,a2))

[[ 99.  27. 100.]
 [ 69.  50.  15.]
 [ 44.  24.  10.]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[3620. 3846. 4072. 4298.]
 [1928. 2062. 2196. 2330.]
 [1112. 1190. 1268. 1346.]]


In [39]:
# log and exp
print(np.log(a1))
print(np.exp(a1))

[[4.59511985 3.29583687 4.60517019]
 [4.2341065  3.91202301 2.7080502 ]
 [3.78418963 3.17805383 2.30258509]]
[[9.88903032e+42 5.32048241e+11 2.68811714e+43]
 [9.25378173e+29 5.18470553e+21 3.26901737e+06]
 [1.28516001e+19 2.64891221e+10 2.20264658e+04]]


In [40]:
# round floor ceil
a=np.random.random((2,3))*100
print(a)
print(np.round(a))
print(np.floor(a))
print(np.ceil(a))

[[81.94072139 68.97253667 76.1931232 ]
 [13.57974456 19.74012411 71.68491496]]
[[82. 69. 76.]
 [14. 20. 72.]]
[[81. 68. 76.]
 [13. 19. 71.]]
[[82. 69. 77.]
 [14. 20. 72.]]


INDEXING


In [41]:
a1=np.arange(20)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

# slicing and indexing
print(a1)
# acess using indexing
print(a1[0],a1[10]) # one and two also



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
0 10


In [42]:
# for 2d arrays
print(a2)
# i want 6
print(a2[1,2])
# 11
print(a2[2,3])



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
11


In [43]:
# FOR 3D (TENSOR) (indexing)
print(a3)
print(a3[0,0,1]) # 1

print(a3[1,1,1]) # 7

# 2 need
print(a3[0,1,0])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
1
7
2


SLICING(imp)

In [44]:
# SLICING IN 1D
print(a1)


# slicing
print(a1[1:6])

# 10 to 12 only

print(a1[10:13])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1 2 3 4 5]
[10 11 12]


In [78]:
# slicing in 2d
print(a2)

# 1st row
print(a2[:1])

# third column
print(a2[:,2])
print(a2[2:]) # 8 9 10 11

# 5 6
# 9 10
print(a2[1:,1:3])


# 0 3
# 8 11
print(a2[::2,::3]) # excusive so 3

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2 3]]
[ 2  6 10]
[[ 8  9 10 11]]
[[ 5  6]
 [ 9 10]]
[[ 0  3]
 [ 8 11]]
