Numpy-- numerical python

In [ ]:
import numpy as np # alias

**Array creation**

In [ ]:
# 1- manual way makig list inside tuple
arr=np.array([1,2,3])
print(arr) #123

# 2 method arange
arr=np.arange(1,10)
print(arr) #123456789

# 3 method
arr=np.array(range(1,10))
print(arr) #123456789


[1 2 3]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


RESHAPE(1d to 2d )

In [ ]:
a=np.arange(12).reshape(2,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [ ]:
# dimensions  and shape of the array
arr=np.array(34)
arr.ndim

0

In [ ]:
# 1 bracket one dimension
# 2 bracket two dimension
a=np.array([]) # 1
a.ndim
b=np.array([[]]) #2 dimension
b.ndim
c= np.array([[[]]]) # 3d
c.ndim
d= np.array([[[[]]]]) # 4d
d.ndim
# check the shape of the array
d.shape #


(1, 1, 1, 0)

In [ ]:
# dtype
a=np.array([1,2,3],dtype=float)
print(a) # behace like float
print(a.dtype) # float64
print(a.astype(np.float32))


[1. 2. 3.]
float64
[1. 2. 3.]
float64


ARRAY CREATION BY GIVINIG RANGE

In [ ]:
 # Giving Range to create no of arrays (loop) np.arange
# range of numbers  ( start stop step )
a=np.arange(1,10)
print(a) # 1 2 3 4 5 6 7 8 9

#  step value

a = np.arange(1,10,2)
print(a) # 1 3 5 7 9

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


LINSPACE -- GENERATE NUMBERS BETWEN -10 TO +10

In [ ]:
# Topic - Array creation linspace -- ( GRAPH )Evenly spaced between two numbers
arr= np.linspace(0,1,5) # 0 to 1
print(arr)  # 0 0.25 0.5 0.75 1.

arr = np.linspace(0,5,10) # need 10 evenly spaced
print(arr)

arr=np.linspace(-10,10,5,dtype=int) # integer type data
print(arr)


[0.   0.25 0.5  0.75 1.  ]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[-10  -5   0   5  10]


In [ ]:
# Logspace --

arr= np.logspace(1,3,3)  # logartihmic scale array 10^1 10^2 10^3 .. 3 points
print(arr)

arr=np.logspace(1,3,2) # 2 points
print(arr)   # 10 1000


[  10.  100. 1000.]
[  10. 1000.]


In [ ]:
#np.logspace(start,ending -> powers,3)

NUMPY ZEROS AND ONES IDENTITY , FULL

In [ ]:
# Topic -- zeroes and ones
# this create an array  full of zeroes np.zeros

arr=np.zeros(5)
print(arr) #  5 elements only

# i  need 2 * 3 matrix of zeroes

a=np.zeros([2,3])
print(a)
print(a.size) # total elements 6



[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
6


In [ ]:
# Ones
arr=np.ones(2) # 2 elements of 1 1
print(arr)

arr = np.ones([2,3]) # 2 * 3
print(arr)

[1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# FULL function
arr = np.full(10,2) # 10 element of 2 (1d array)
print(arr)

[2 2 2 2 2 2 2 2 2 2]


IDENTITY (NP.IDENETIY)

In [ ]:
a=np.identity(3)
print(a) # diagonal matrix 3 by 3 matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 2d array
# parameters - ([rows, colummns ], default value )

arr = np.full([2,3],7) # 2,3 matrix of 6 elements of 7 predefault 7 values
print(arr)

[[7 7 7]
 [7 7 7]]


In [ ]:
# uninitalized array - create an array  without setting any sorting any values
arr=np.empty([2,3]) # pass dimensions this is uninitialized arrayz
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
list=[1,2,3,4,5]
a=list*2
print(a)
arr = np.array([1,2,3,4,5])
b= arr * 2
print(b)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [ ]:
# Numpy Data Types and Type casting
arr = np.array([1,2,4,5,5])
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
lst=[1,2,3,4,5]
arr= np.array(lst)
print(arr)
print(type(arr))
print(arr.dtype) #int 64


[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


converted to float 32 and float 64

In [ ]:
arr = np.array([1,2,3,4],dtype=  np.float32)
print(arr.dtype)

arr = np.array([1,2,3,4,5],dtype=np.float64)
print(arr.dtype) #float64

float32
float64


Float to int reverse

In [ ]:
arr = np.array([1.1,2.1,3,4],dtype=  np.int32)
print(arr.dtype)

int32


In [ ]:
# Typecasting - covert one datatype to another datatype
# astype
arr=np.array([1,2,3])
print(arr.dtype) # default datatype is int 64 or float 64

int64


CONVERT INT64 TO FLOAT64

In [ ]:
a=np.array([1,2,3])
new_arr=a.astype(np.float64)
print(new_arr)

# if we check datatype now
print(new_arr.dtype) # float64

[1. 2. 3.]
float64


In [ ]:
# Type Casting Erros
"""arr=np.array(["1","2","hello"])
arr2=arr.astype(np.int64)
print(arr2) # invalid hello multiple chacters"""

# we cannot covert string into integer or vice versa
# only same type of data contains

'arr=np.array(["1","2","hello"])\narr2=arr.astype(np.int64)\nprint(arr2) # invalid hello multiple chacters'

-->> we can create 2d 3d 4d as onn


In [ ]:
a = np.array([1,2,3])
b=np.array([[1,2,3],
            [4,5,6]])
c=np.array([[[1,2],[3,4],[5,6]]])

# lets check there dimensions
print(a.ndim)  #1
print(b.ndim)  #2
print(c.ndim)  #3

# shape check
print(a.shape)
print(b.shape)
print(c.shape)

# also change or check datatype
d=np.array([1,2,3],dtype=float)
print(d)

# reshape
a=np.arange(1,11)
a.reshape(5,2)
a=np.random.random((1,11))
print(a)

1
2
3
(3,)
(2, 3)
(1, 3, 2)
[1. 2. 3.]
[[0.84566842 0.9481732  0.31982324 0.0634297  0.2587688  0.98035591
  0.72810974 0.47884269 0.66934863 0.57990381 0.34400408]]


**ARRAY ATTRIBUTES  (size , shape ,ndim, itemsize, dtype)**

In [ ]:
a1=np.arange(1,11)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

#ndim-
a1.ndim
a2.ndim
a3.ndim
a1.shape
a2.shape
a3.shape
a1.size
a2.size
a3.size

# itemsize
a=a1.itemsize
print(a)

#dtype tells type
print(a1.dtype)  # int64

# changing datatype
#astype
a3.astype(np.int32)

8
int64


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [ ]:
# ndim nshape nsize itemsizd

------------------Questtions ---


In [ ]:
import numpy as np
arr=np.random.rand(10).reshape(2,5)
print(arr)

[[0.93029089 0.45393584 0.49228696 0.64366537 0.98007166]
 [0.88595944 0.50899823 0.44098001 0.310765   0.65118411]]


In [ ]:
arr=np.ones(12).reshape(2,6)
print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


Array operations

In [2]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

NameError: name 'np' is not defined