<a href="https://colab.research.google.com/github/Deepanshu-8126/Numpy-/blob/main/01_array_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np # alias



In [16]:
arr=np.array([1,2,3])
arr.ndim

1

In [17]:
# dimensions  and shape of the array
arr=np.array(34)
arr.ndim

0

In [18]:
# 1 bracket one dimension
# 2 bracket two dimension
a=np.array([]) # 1
a.ndim
b=np.array([[]]) #2 dimension
b.ndim
c= np.array([[[]]]) # 3d
c.ndim
d= np.array([[[[]]]]) # 4d
d.ndim
# check the shape of the array
d.shape #


(1, 1, 1, 0)

In [19]:
 # Giving Range to create no of arrays (loop) np.arange
# range of numbers  ( start stop step )
a=np.arange(1,10)
print(a) # 1 2 3 4 5 6 7 8 9

#  step value

a = np.arange(1,10,2)
print(a) # 1 3 5 7 9

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [20]:
# Topic - linspace -- Evenly spaced between two numbers
arr= np.linspace(0,1,5) # 0 to 1
print(arr)  # 0 0.25 0.5 0.75 1.

arr = np.linspace(0,5,10) # need 10 evenly spaced
print(arr)


[0.   0.25 0.5  0.75 1.  ]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [21]:
# Logspace --

arr= np.logspace(1,3,3)  # logartihmic scale array 10^1 10^2 10^3 .. 3 points
print(arr)

arr=np.logspace(1,3,2) # 2 points
print(arr)   # 10 1000


[  10.  100. 1000.]
[  10. 1000.]


In [28]:
#np.logspace(start,ending -> powers,3)

In [ ]:
# Topic -- zeroes and ones
# this create an array  full of zeroes np.zeros

arr=np.zeros(5)
print(arr) #  5 elements only

# i  need 2 * 3 matrix of zeroes

a=np.zeros([2,3])
print(a)
print(a.size) # total elements 6



In [ ]:
# Ones
arr=np.ones(2) # 2 elements of 1 1
print(arr)

arr = np.ones([2,3]) # 2 * 3
print(arr)

In [ ]:
# FULL function
arr = np.full(10,2) # 10 element of 2 (1d array)
print(arr)

In [23]:
# 2d array
# parameters - ([rows, colummns ], default value )

arr = np.full([2,3],7) # 2,3 matrix of 6 elements of 7 predefault 7 values
print(arr)

[[7 7 7]
 [7 7 7]]


In [24]:
# uninitalized array - create an array  without setting any sorting any values
arr=np.empty([2,3]) # pass dimensions this is uninitialized arrayz
print(arr)

[[3.04798032e-315 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [25]:
list=[1,2,3,4,5]
a=list*2
print(a)
arr = np.array([1,2,3,4,5])
b= arr * 2
print(b)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [26]:
# Numpy Data Types and Type casting
arr = np.array([1,2,4,5,5])
print(type(arr))

<class 'numpy.ndarray'>


In [29]:
lst=[1,2,3,4,5]
arr= np.array(lst)
print(arr)
print(type(arr))
print(arr.dtype) #int 64


[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


converted to float 32 and float 64

In [34]:
arr = np.array([1,2,3,4],dtype=  np.float32)
print(arr.dtype)

arr = np.array([1,2,3,4,5],dtype=np.float64)
print(arr.dtype) #float64

float32
float64


Float to int reverse

In [35]:
arr = np.array([1.1,2.1,3,4],dtype=  np.int32)
print(arr.dtype)

int32


In [37]:
# Typecasting - covert one datatype to another datatype
# astype
arr=np.array([1,2,3])
print(arr.dtype) # default datatype is int 64 or float 64

int64


CONVERT INT64 TO FLOAT64

In [41]:
a=np.array([1,2,3])
new_arr=a.astype(np.float64)
print(new_arr)

# if we check datatype now
print(new_arr.dtype) # float64

[1. 2. 3.]
float64


In [42]:
# Type Casting Erros
arr=np.array(["1","2","hello"])
arr2=arr.astype(np.int64)
print(arr2) # invalid hello multiple chacters

# we cannot covert string into integer or vice vers

ValueError: invalid literal for int() with base 10: np.str_('hello')