<a href="https://colab.research.google.com/github/Deepanshu-8126/Numpy-/blob/main/02_array_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
# Array Creation #--2
import numpy as np
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
print(a1)
print(a2)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [6]:
# scalar operations / arithmethic
print(a1*2)
print(a1+2)
print(a1-2)
print(a1%2)
print(a1/2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]


In [14]:
# Relational operations
print(a1)
print(a1>5)
print(a1==5)
print(a1!=5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[[False False False False]
 [False  True False False]
 [False False False False]]
[[ True  True  True  True]
 [ True False  True  True]
 [ True  True  True  True]]


In [20]:
# Vector operations arithmetic  "3d item wise add first item of a1 + first item of a2 as it soon "
print(a1)
print(a2)
print(a1+a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


In [28]:
# Array functions
a1=np.arange(1,11)
a2=np.random.random((3,3))  # float value  return by default
print(a1)
print(a2)
round=np.round(a2)
print(round)
print(np.sum(a1))



[ 1  2  3  4  5  6  7  8  9 10]
[[0.55452382 0.25654895 0.49680766]
 [0.64656289 0.21490012 0.92772891]
 [0.43529801 0.74557753 0.09344411]]
[[1. 0. 0.]
 [1. 0. 1.]
 [0. 1. 0.]]
55


In [34]:
print(np.max(a1))
print(np.min(a2))
print(np.sum(a1))
print(np.prod(a1))



10
0.09344410524031355
55
3628800


In [49]:
# for particular row or column perform operation
a=np.arange(1,10).reshape(3,3)
print(a)
print(np.max(a,axis=0)) # 7 8 9
print(np.min(a,axis=1))

# sum and product
print(np.sum(a,axis=1))
print(np.prod(a,axis=0))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[7 8 9]
[1 4 7]
[ 6 15 24]


In [50]:
# mean median std var
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))

5.0
5.0
2.581988897471611
6.666666666666667


In [55]:
# mean medain var standard deviation range axis wise
print(np.mean(a,axis=1))
print(np.median(a,axis=1))
print(np.var(a,axis=1))
print(np.std(a,axis=1))

[2. 5. 8.]
