<a href="https://colab.research.google.com/github/Deepanshu-8126/Numpy-/blob/main/numpy_fudamentals_campusxnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy array vs Python lists

In [36]:
# numpy
import numpy as np
a=np.arange(10000000)
b=np.arange(10000000,20000000)
start=time.time()
c=a+b
print(time.time()-start)

0.033225297927856445


In [37]:
# advanced indexing
a=np.arange(12).reshape(4,3)
print(a)
print(a[1:3,1:3])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[4 5]
 [7 8]]


In [38]:
# two new methods
# fancy indexing, bollean indexing
#item fetch
print(a[[0,2,3]])

[[ 0  1  2]
 [ 6  7  8]
 [ 9 10 11]]


In [39]:
a=np.arange(24).reshape(6,4)
print(a[[0,3,4,5]])

[[ 0  1  2  3]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [40]:
# if columnn we need 1,3,5 use  fancy indexing
print(a)
a[:,[0,2,3]]



# mostly use in pandaas

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [41]:
#Boolean indexing
# find all numbers greater than 50
print(a)
print(a>50)#bollean return

print(a[a>50]) # it filter out that data which are greater than 50 only that data

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]
[]


In [44]:
# find all the numbers greater than  50
print(a[a<50])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [66]:
a=np.arange(1,11).reshape(2,5)
print(a)

# filter out using boolean indexing  even numbers
print(a%2==0)

# i need only the data which is even other not
print(a[a%2==0]) # 2 4 6  8 10


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[False  True False  True False]
 [ True False  True False  True]]
[ 2  4  6  8 10]


In [78]:
# question -- find all the numbers greater than 50 and are even
a=np.arange(1,11).reshape(2,5)
print(a)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [80]:
# exmaple find all numbers not divisble by 7
print(a)
print(a[a%7!=0])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  8  9 10]


Broadcasting
