<a href="https://colab.research.google.com/github/Deepanshu-8126/Numpy-/blob/main/numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# SORTING (sort) np.sort
# Return a sorted copy of an array
import numpy as np
a=np.random.randint(1,100,15)
b=np.random.randint(1,100,24).reshape(6,4)
print(a)
print(b)

# sort
print(np.sort(a)) # aascending order sorting



[55 57 16 69 73 71 46 79 27 19 44 94 20  5 70]
[[89 26 99 70]
 [46 63 15 82]
 [70 40 94 49]
 [52 94 59 30]
 [ 1  2 36 33]
 [31 77 14 21]]
[ 5 16 19 20 27 44 46 55 57 69 70 71 73 79 94]


In [5]:
# descending order sorting
print(np.sort(a)[::-1])

[94 79 73 71 70 69 57 55 46 44 27 20 19 16  5]


In [18]:
# row wise and column wise sorting using axis
print(b)
np.sort(b,axis=0)
np.sort(b,axis=1) # column wise


[[89 26 99 70]
 [46 63 15 82]
 [70 40 94 49]
 [52 94 59 30]
 [ 1  2 36 33]
 [31 77 14 21]]


array([[26, 70, 89, 99],
       [15, 46, 63, 82],
       [40, 49, 70, 94],
       [30, 52, 59, 94],
       [ 1,  2, 33, 36],
       [14, 21, 31, 77]])

In [29]:
# 2- function np.append
print(a)
print(np.append(a,200)) # append add on the last


# for 2d array
print(np.append(b,np.ones((b.shape[0],1)),axis=1))  # row

# column
print(np.append(b,np.random.random((b.shape[0],1)),axis=1))

[55 57 16 69 73 71 46 79 27 19 44 94 20  5 70]
[ 55  57  16  69  73  71  46  79  27  19  44  94  20   5  70 200]
[[89. 26. 99. 70.  1.]
 [46. 63. 15. 82.  1.]
 [70. 40. 94. 49.  1.]
 [52. 94. 59. 30.  1.]
 [ 1.  2. 36. 33.  1.]
 [31. 77. 14. 21.  1.]]
[[89.         26.         99.         70.          0.83440356]
 [46.         63.         15.         82.          0.69597477]
 [70.         40.         94.         49.          0.5505067 ]
 [52.         94.         59.         30.          0.28100137]
 [ 1.          2.         36.         33.          0.29887737]
 [31.         77.         14.         21.          0.39813059]]
