<a href="https://colab.research.google.com/github/Deepanshu-8126/Numpy-/blob/main/numpy_fudamentals_campusxnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy array vs Python lists

In [13]:
# numpy
"""import numpy as np
a=np.arange(10000000)
b=np.arange(10000000,20000000)
start=time.time()
c=a+b
print(time.time()-start)"""

'import numpy as np\na=np.arange(10000000)\nb=np.arange(10000000,20000000)\nstart=time.time()\nc=a+b\nprint(time.time()-start)'

In [14]:
# advanced indexing
a=np.arange(12).reshape(4,3)
print(a)
print(a[1:3,1:3])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[4 5]
 [7 8]]


In [15]:
# two new methods
# fancy indexing, bollean indexing
#item fetch
print(a[[0,2,3]])

[[ 0  1  2]
 [ 6  7  8]
 [ 9 10 11]]


In [16]:
a=np.arange(24).reshape(6,4)
print(a[[0,3,4,5]])

[[ 0  1  2  3]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [17]:
# if columnn we need 1,3,5 use  fancy indexing
print(a)
a[:,[0,2,3]]



# mostly use in pandaas

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [18]:
#Boolean indexing
# find all numbers greater than 50
print(a)
print(a>50)#bollean return

print(a[a>50]) # it filter out that data which are greater than 50 only that data

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]
[]


In [19]:
# find all the numbers greater than  50
print(a[a<50])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [20]:
a=np.arange(1,11).reshape(2,5)
print(a)

# filter out using boolean indexing  even numbers
print(a%2==0)

# i need only the data which is even other not
print(a[a%2==0]) # 2 4 6  8 10


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[False  True False  True False]
 [ True False  True False  True]]
[ 2  4  6  8 10]


In [21]:
# question -- find all the numbers greater than 50 and are even
a=np.arange(1,11).reshape(2,5)
print(a)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [22]:
# exmaple find all numbers not divisble by 7
print(a)
print(a[a%7!=0])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  8  9 10]


Broadcasting


In [23]:
# Working with mathematical formulaas
# How numpy trats two diffrent numpy array during arithmethic operations

# the smaller array is broadcast accross the larger array so that they have
# shape , How?
import numpy as np
a=np.arange(6).reshape(2,3)
b=np.arange(3).reshape(1,3)
print(a)
print(b)

print(a+b) # two different shape we can add

# broadcast when we have different shape array
#smaller array  we make larger 'broadcast' so that we have compatible with longger shape for artihmethic operations


# Rules
# 1-- Make the two arrays have th same number of dimensions
# means if 1d -- convert to 2d

# 2-- Make each dimension of the two array of the same size
# (3,3)   (3,) --- (1,3) -- (3,3)  strecth




[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


In [24]:
# Question-
"""a=np.arange(12).reshape(3,4)
b=np.arange(12).reshape(4,3)
print(a)
print(b)
print(a+b)  # this raises an error 3,4 4,3 no work"""



'a=np.arange(12).reshape(3,4)\nb=np.arange(12).reshape(4,3)\nprint(a)\nprint(b)\nprint(a+b)  # this raises an error 3,4 4,3 no work'