<a href="https://colab.research.google.com/github/Deepanshu-8126/Numpy-/blob/main/numpy_fudamentals_campusxnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy array vs Python lists

In [3]:
# numpy
import numpy as np
a=np.arange(10000000)
b=np.arange(10000000,20000000)
start=time.time()
c=a+b
print(time.time()-start)

NameError: name 'time' is not defined

In [ ]:
# advanced indexing
a=np.arange(12).reshape(4,3)
print(a)
print(a[1:3,1:3])

In [ ]:
# two new methods
# fancy indexing, bollean indexing
#item fetch
print(a[[0,2,3]])

In [ ]:
a=np.arange(24).reshape(6,4)
print(a[[0,3,4,5]])

In [ ]:
# if columnn we need 1,3,5 use  fancy indexing
print(a)
a[:,[0,2,3]]



# mostly use in pandaas

In [ ]:
#Boolean indexing
# find all numbers greater than 50
print(a)
print(a>50)#bollean return

print(a[a>50]) # it filter out that data which are greater than 50 only that data

In [ ]:
# find all the numbers greater than  50
print(a[a<50])

In [ ]:
a=np.arange(1,11).reshape(2,5)
print(a)

# filter out using boolean indexing  even numbers
print(a%2==0)

# i need only the data which is even other not
print(a[a%2==0]) # 2 4 6  8 10


In [ ]:
# question -- find all the numbers greater than 50 and are even
a=np.arange(1,11).reshape(2,5)
print(a)


In [ ]:
# exmaple find all numbers not divisble by 7
print(a)
print(a[a%7!=0])

Broadcasting


In [13]:
# Working with mathematical formulaas
# How numpy trats two diffrent numpy array during arithmethic operations

# the smaller array is broadcast accross the larger array so that they have
# shape , How?
import numpy as np
a=np.arange(6).reshape(2,3)
b=np.arange(3).reshape(1,3)
print(a)
print(b)

print(a+b) # two different shape we can add

# broadcast when we have different shape array
#smaller array  we make larger 'broadcast' so that we have compatible with longger shape for artihmethic operations


# Rules
# 1-- Make the two arrays have th same number of dimensions
# means if 1d -- convert to 2d

# 2-- Make each dimension of the two array of the same size
# (3,3)   (3,) --- (1,3) -- (3,3)  strecth


[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]
